# Generated by Django 2.1 on 2019-04-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField(null=True)),
                ('branch_name', models.CharField(max_length=15)),
                ('bank_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Bank')),
            ],
        ),
    ]
