# Generated by Django 2.1 on 2019-04-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190420_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Signin',
        ),
    ]
