# Generated by Django 2.0.2 on 2020-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200107_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std',
        ),
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
