# Generated by Django 2.0.2 on 2020-01-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200107_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
